### ISSUE TITLE
Add Missing Methods for Execution details

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-elixir#18]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Execution details

Missing methods:

Get Execution Details - https://docs.novu.co/api-reference/execution-details/get-execution-details

**Comment by unicodeveloper** [comment]
Assigning this to you right now @sccalabr

**Comment by unicodeveloper** [comment]
Assigned ⭐

**Comment by unicodeveloper** [comment]
Assigned ⭐

**Comment by unicodeveloper** [comment]
You can hit the endpoint from the documentation to see how it works and the responses it returnes. I added the reference link. Grab your API key from https://web.novu.co/settings and use it to test it in the docs link. @sccalabr 

![CleanShot 2023-10-09 at 09 12 48](https://github.com/novuhq/novu-elixir/assets/2946769/e28a2aae-2fd4-4b11-b143-4d2b26b5e42c)
