### ISSUE TITLE
Add Missing Methods for Messages

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-elixir#20]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Messages

Missing methods:

Get Messages - https://docs.novu.co/api-reference/messages/get-messages
Delete Message - https://docs.novu.co/api-reference/messages/delete-message

**Comment by unicodeveloper** [comment]
Assigning this to you right now @sccalabr

**Comment by unicodeveloper** [comment]
Assigned ⭐
