### ISSUE TITLE
Add Missing Methods for Blueprints

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-elixir#21]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Blueprints

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/default/BlueprintController_getGroupedBlueprints) and add the missing ones.

**Comment by AnuragNishad12** [comment]
Hii @Cliftonz i want to ask that from where i get the method so that i can add it

**Comment by btkostner** [comment]
@AnuragNishad12 You can find the endpoint from the [link posted in the issue body](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup). You can see an example of how we make HTTP calls in the [already existing modules](https://github.com/novuhq/novu-elixir/blob/main/lib/novu/subscribers.ex), though this will require creating a new module.

**Comment by unicodeveloper** [comment]
You can also check the Blue prints API reference documentation.

1. https://docs.novu.co/api-reference/get-v1blueprintsgroup-by-category
2. https://docs.novu.co/api-reference/get-v1blueprints 

These are what's missing from the SDK @AnuragNishad12

**Comment by unicodeveloper** [comment]
@AnuragNishad12 Any updates?
